plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version "[7.0.17,8)"
    id 'net.minecraftforge.jarjar' version '0.2.3'
    id 'idea'
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

jarJar.register() {
    archiveClassifier = null
}

jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        client {
            workingDir = file('runs/client')
            args "--mixin.config=${mod_id}.mixins.json"
            args "--mixin.config=${mod_id}.forge.mixins.json"

            mods {
                modClientRun {
                    source sourceSets.main
                    source project(':common').sourceSets.main
                }
            }
        }

        server {
            workingDir = file('runs/server')
            args "--mixin.config=${mod_id}.mixins.json"
            args "--mixin.config=${mod_id}.forge.mixins.json"

            mods {
                modServerRun {
                    source sourceSets.main
                    source project(':common').sourceSets.main
                }
            }
        }

        data {
            workingDir = file('runs/data')
            args "--mixin.config=${mod_id}.mixins.json"
            args "--mixin.config=${mod_id}.forge.mixins.json"
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                modDataRun {
                    source sourceSets.main
                    source project(':common').sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    minecraft.mavenizer(it)
    maven { url = uri(layout.projectDirectory.dir('../.gradle/mavenizer/repo')) }
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'

    implementation "org.greenrobot:eventbus-java:3.3.1"
    jarJar "org.greenrobot:eventbus-java:3.3.1"
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
