modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "${portability_test_mod_id}"
version = "${version}"
displayName = "ZBB Portability GameTests"

[[dependencies.${portability_test_mod_id}]]
modId = "${mod_id}"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
